In [1]:
import numpy as np 

In [13]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
t = np.linalg.inv(array1)
print(np.dot(t,array1))
print("是")


[[1. 0.]
 [0. 1.]]
是


In [16]:
#2. 運用上列array計算特徵值、特徵向量?
w,v = np.linalg.eig(array1)
w,v

(array([13.,  2.]),
 array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [18]:
#3. 運用上列array計算SVD?
u,s,vh = np.linalg.svd(array1)
u,s,vh

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))